fix(deps): update to ruby 3.4.4 to workaround compilation error on macos 15.5
compilation error:
```
./vm_callinfo.h:218:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
```